/**
 * Generate src/db/seed.sql with realistic, always-near-future demo data.
 *
 * Run: `bun run db:generate-seed` (then `bun run db:seed:local`).
 * Slots are produced for the next ~14 weekdays from today, so a re-seed always
 * yields bookable future appointments. Times are London wall-clock, converted to
 * the UTC instants stored in D1. Synthetic data only (SECURITY.md).
 */
import { writeFileSync } from 'node:fs';

const TZ = 'Europe/London';

/** Minutes Europe/London is ahead of UTC at a given instant (handles BST/GMT). */
function londonOffsetMinutes(utc: Date): number {
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone: TZ,
    hour12: false,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  })
    .formatToParts(utc)
    .reduce<Record<string, string>>((a, p) => ((a[p.type] = p.value), a), {});
  const asUtc = Date.UTC(
    +parts.year!,
    +parts.month! - 1,
    +parts.day!,
    +parts.hour!,
    +parts.minute!,
    +parts.second!,
  );
  return (asUtc - utc.getTime()) / 60000;
}

/** London wall-clock (y,m,d,h,mi) -> stored UTC ISO string. */
function londonToUtcIso(y: number, mo: number, d: number, h: number, mi: number): string {
  let ts = Date.UTC(y, mo - 1, d, h, mi);
  for (let i = 0; i < 2; i++)
    ts = Date.UTC(y, mo - 1, d, h, mi) - londonOffsetMinutes(new Date(ts)) * 60000;
  return new Date(ts).toISOString().replace('.000Z', 'Z');
}

const practitioners = [
  { id: 'gp-okafor', name: 'Dr Sarah Okafor', role: 'GP', specialty: 'General practice' },
  { id: 'gp-patel', name: 'Dr Raj Patel', role: 'GP', specialty: 'General practice' },
  { id: 'gp-campbell', name: 'Dr Fiona Campbell', role: 'GP', specialty: "Women's health" },
  {
    id: 'dentist-hughes',
    name: 'Ms Alice Hughes',
    role: 'Dentist',
    specialty: 'General dentistry',
  },
  {
    id: 'dentist-boateng',
    name: 'Mr Kofi Boateng',
    role: 'Dentist',
    specialty: 'General dentistry',
  },
] as const;

const patients = [
  {
    id: 'p-tomlin',
    first: 'John',
    last: 'Tomlin',
    dob: '1979-11-05',
    phone: '07700900001',
    email: 'john.tomlin@example.com',
  },
  {
    id: 'p-ahmed',
    first: 'Yusuf',
    last: 'Ahmed',
    dob: '1990-06-14',
    phone: '07700900002',
    email: 'yusuf.ahmed@example.com',
  },
  {
    id: 'p-clarke',
    first: 'Emily',
    last: 'Clarke',
    dob: '2001-01-30',
    phone: '07700900003',
    email: 'emily.clarke@example.com',
  },
  {
    id: 'p-nowak',
    first: 'Marta',
    last: 'Nowak',
    dob: '1966-09-09',
    phone: '07700900004',
    email: 'marta.nowak@example.com',
  },
  {
    id: 'p-reid',
    first: 'Grace',
    last: 'Reid',
    dob: '1958-12-01',
    phone: '07700900005',
    email: 'grace.reid@example.com',
  },
  {
    id: 'p-osborne',
    first: 'Daniel',
    last: 'Osborne',
    dob: '1988-07-19',
    phone: '07700900006',
    email: 'daniel.osborne@example.com',
  },
] as const;

// London wall-clock slot times per practitioner type.
const GP_TIMES = ['09:00', '09:10', '09:20', '09:30', '11:00', '11:10', '15:00', '15:10'];
const DENTIST_TIMES = ['09:00', '09:20', '09:40', '14:00', '14:20'];

const esc = (s: string) => s.replace(/'/g, "''");

function build(): string {
  const lines: string[] = [
    '-- GENERATED by scripts/generate-seed.ts — do not edit by hand.',
    '-- Synthetic demo data. Re-run `bun run db:generate-seed` to refresh dates.',
    'PRAGMA foreign_keys = ON;',
    'DELETE FROM emails;',
    'DELETE FROM events;',
    'DELETE FROM escalations;',
    'DELETE FROM appointments;',
    'DELETE FROM slots;',
    'DELETE FROM call_logs;',
    'DELETE FROM patients;',
    'DELETE FROM practitioners;',
    '',
  ];

  for (const p of practitioners) {
    lines.push(
      `INSERT INTO practitioners (id, name, role, specialty) VALUES ('${p.id}', '${esc(p.name)}', '${p.role}', '${esc(p.specialty)}');`,
    );
  }
  lines.push('');
  for (const p of patients) {
    lines.push(
      `INSERT INTO patients (id, first_name, last_name, dob, phone, email) VALUES ('${p.id}', '${esc(p.first)}', '${esc(p.last)}', '${p.dob}', '${p.phone}', '${esc(p.email)}');`,
    );
  }
  lines.push('');

  const today = new Date();
  let added = 0;
  for (let dayOffset = 1; dayOffset <= 20 && added < 14; dayOffset++) {
    const d = new Date(
      Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate() + dayOffset),
    );
    const dow = d.getUTCDay();
    if (dow === 0 || dow === 6) continue; // skip weekends
    added++;
    const [y, mo, da] = [d.getUTCFullYear(), d.getUTCMonth() + 1, d.getUTCDate()];
    const stamp = `${y}${String(mo).padStart(2, '0')}${String(da).padStart(2, '0')}`;
    for (const pr of practitioners) {
      const times = pr.role === 'Dentist' ? DENTIST_TIMES : GP_TIMES;
      const dur = pr.role === 'Dentist' ? 20 : 10;
      for (const t of times) {
        const [h, mi] = t.split(':').map(Number);
        const iso = londonToUtcIso(y, mo, da, h!, mi!);
        const id = `slot-${pr.id}-${stamp}-${t.replace(':', '')}`;
        lines.push(
          `INSERT INTO slots (id, practitioner_id, starts_at, duration_minutes, status) VALUES ('${id}', '${pr.id}', '${iso}', ${dur}, 'available');`,
        );
      }
    }
  }
  lines.push('');
  return lines.join('\n');
}

writeFileSync(new URL('../src/db/seed.sql', import.meta.url), build());
console.log('Wrote src/db/seed.sql');
